---
title: "Trends within All-NBA Team Data"
author: "Spencer Tabit"
output: html_document
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'index.html')) })
---

#Introduction




#Required Tools





```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(purrr)
library(rvest)
library(magrittr)
library(stringr)
library(broom)
library(knitr)
```

#Tidying Up Data

```{r message = FALSE, warning=FALSE}
setwd("~/College/CMSC320/Final Project/data/regularSeason")

regular_seasons <- 
  rbind(
    read_csv("nba_1988-89.csv") %>% mutate(season = "1988-89"),
    read_csv("nba_1989-90.csv") %>% mutate(season = "1989-90")
  ) %>%
  rbind(
    read_csv("nba_1990-91.csv") %>% mutate(season = "1990-91")
  ) %>%
  rbind(
    read_csv("nba_1991-92.csv") %>% mutate(season = "1991-92")
  ) %>%
  rbind (
    read_csv("nba_1992-93.csv") %>% mutate(season = "1992-93")
  ) %>%
  rbind(
    read_csv("nba_1993-94.csv") %>% mutate(season = "1993-94")
  ) %>%
  rbind(
    read_csv("nba_1994-95.csv") %>% mutate(season = "1994-95")
  ) %>%
  rbind(
    read_csv("nba_1995-96.csv") %>% mutate(season = "1995-96")
  ) %>%
  rbind(
    read_csv("nba_1996-97.csv") %>% mutate(season = "1996-97")
  ) %>%
  rbind(
    read_csv("nba_1997-98.csv") %>% mutate(season = "1997-98")
  ) %>%
  rbind(
    read_csv("nba_1998-99.csv") %>% mutate(season = "1998-99")
  ) %>%
  rbind(
    read_csv("nba_1999-00.csv") %>% mutate(season = "1999-00")
  ) %>% 
  rbind(
    read_csv("nba_2000-01.csv") %>% mutate(season = "2000-01")
  ) %>% 
  rbind(
    read_csv("nba_2001-02.csv") %>% mutate(season = "2001-02")
  ) %>% 
  rbind(
    read_csv("nba_2002-03.csv") %>% mutate(season = "2002-03")
  ) %>% 
  rbind(
    read_csv("nba_2003-04.csv") %>% mutate(season = "2003-04")
  ) %>% 
  rbind(
    read_csv("nba_2004-05.csv") %>% mutate(season = "2004-05")
  ) %>% 
  rbind(
    read_csv("nba_2005-06.csv") %>% mutate(season = "2005-06")
  ) %>% 
  rbind(
    read_csv("nba_2006-07.csv") %>% mutate(season = "2006-07")
  ) %>% 
  rbind(
    read_csv("nba_2007-08.csv") %>% mutate(season = "2007-08")
  ) %>% 
  rbind(
    read_csv("nba_2008-09.csv") %>% mutate(season = "2008-09")
  ) %>% 
  rbind(
    read_csv("nba_2009-10.csv") %>% mutate(season = "2009-10")
  ) %>% 
  rbind(
    read_csv("nba_2010-11.csv") %>% mutate(season = "2010-11")
  ) %>% 
  rbind(
    read_csv("nba_2011-12.csv") %>% mutate(season = "2011-12")
  ) %>% 
  rbind(
    read_csv("nba_2012-13.csv") %>% mutate(season = "2012-13")
  ) %>% 
  rbind(
    read_csv("nba_2013-14.csv") %>% mutate(season = "2013-14")
  ) %>% 
  rbind(
    read_csv("nba_2014-15.csv") %>% mutate(season = "2014-15")
  ) %>% 
  rbind(
    read_csv("nba_2015-16.csv") %>% mutate(season = "2015-16")
  ) %>% 
  rbind(
    read_csv("nba_2016-17.csv") %>% mutate(season = "2016-17")
  ) %>% 
  rbind(
    read_csv("nba_2017-18.csv") %>% mutate(season = "2017-18")
  ) %>%
  mutate(player = str_trim(Name)) %>%
  select(-Name)


regular_seasons
```
#Web Scrapping and Cleaning Data
```{r message = FALSE, warning=FALSE}
all_nba_team_players_url <- "https://en.wikipedia.org/wiki/All-NBA_Team"

all_nba_team_players_data <- all_nba_team_players_url %>%
  read_html() %>%
  html_node("#mw-content-text > div > table:nth-child(24)") %>%
  html_table(fill=TRUE) %>%
  set_colnames(c("season", "first_players", "first_players_team", "second_players", "second_players_team", "third_players", "third_players_team")) %>%
  as_tibble()

all_nba_team_players_data <- all_nba_team_players_data %>%
  slice(2:151)

all_nba_team_first_data <- all_nba_team_players_data %>%
  select(season, first_players) %>%
  mutate(is_all_nba = "Yes") %>%
  mutate(player = first_players) %>%
  select(season, player, is_all_nba)
  


all_nba_team_second_data <- all_nba_team_players_data %>%
  select(season, second_players) %>%
  mutate(is_all_nba = "Yes") %>%
  mutate(player = second_players) %>%
  select(season, player, is_all_nba)

all_nba_team_third_data <- all_nba_team_players_data %>%
  select(season, third_players) %>%
  mutate(is_all_nba = "Yes") %>%
  mutate(player = third_players) %>%
  select(season, player, is_all_nba)

all_nba_team_players_data <- all_nba_team_first_data %>%
  full_join(all_nba_team_second_data, by= c("season", "player", "is_all_nba")) %>%
  full_join(all_nba_team_third_data, by =c("season", "player", "is_all_nba")) %>%
  arrange(season)

all_nba_team_players_data <- all_nba_team_players_data %>%
  mutate(player = str_extract(player, "^(\\w|'|-)* [A-Za-z]*")) %>%
  mutate(season = str_c(str_extract(season, "^\\d*"),str_extract(str_trim(season), "\\d*$"), sep = "-"))

all_nba_team_players_data
```  
#Putting the data together
```{r}
  
regular_seasons <- regular_seasons %>%
  left_join(all_nba_team_players_data, by = c("player", "season")) %>%
  mutate(is_all_nba = if_else(is.na(is_all_nba), "No", "Yes"))

regular_seasons
``` 
#Exploratory Data Analysis, Graphing, and Linear Regression
```{r}
threes_per_season <- regular_seasons%>%
  group_by(season) %>%
  summarize(sum_of_3PA = sum(`3PA`)) %>%
  mutate(season = strtoi(str_extract(season, "^\\d*")))

threes_per_season %>%
  ggplot(aes(x=season, y =sum_of_3PA)) +
  geom_bar(stat = "identity") +
  geom_smooth(method = lm) +
  labs(title="Three Pointers Attempted Per Season",
         x = "Season",
         y = "Three Pointers Attempted") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5))
```

```{r}
threes_per_season_fit <- lm(sum_of_3PA~season, data=threes_per_season)

threes_per_season_stats <- threes_per_season_fit %>%
  tidy()

threes_per_season_stats
```


```{r}
average_players <- regular_seasons%>%
  group_by(is_all_nba) %>%
  summarise(mean_EFF = mean(EFF), mean_PTS = mean(PTS), mean_REB = mean(REB), mean_AST = mean(AST), mean_STL = mean(STL), mean_BLK = mean(BLK), mean_TOV = mean(TOV))

average_players
```


```{r}
regular_seasons%>%
  ggplot(aes(x=season, y =EFF, color = is_all_nba)) +
  geom_point() +
  geom_smooth(method=lm) +
  labs(title="Efficiency by Season",
         x = "Season",
         y = "Efficiency") +
  theme(axis.text.x = element_text(angle=90, vjust=0.5))
```

#Classification
```{r}
library(MASS)
all_nba_fit1 <- lda(as.factor(is_all_nba) ~ EFF, regular_seasons)
lda_pred <- predict(all_nba_fit1, data=regular_seasons)
print(table(predicted=lda_pred$class, observed=regular_seasons$is_all_nba))

``` 

```{r}
all_nba_fit2 <- lda(as.factor(is_all_nba) ~ EFF * PTS * REB, regular_seasons)
lda_pred2 <- predict(all_nba_fit2, data=regular_seasons)
print(table(predicted=lda_pred2$class, observed=regular_seasons$is_all_nba))
``` 

```{r echo=FALSE}
library(ROCR)

pred2 <- prediction(lda_pred2$posterior[,"Yes"], regular_seasons$is_all_nba)

layout(cbind(1,2))
plot(performance(pred2, "tpr"))
plot(performance(pred2, "fpr"))
``` 

```{r}
auc <- unlist(performance(pred2, "auc")@y.values)
plot(performance(pred2, "tpr", "fpr"), 
     main=paste("LDA AUROC=", round(auc, 2)), 
     lwd=1.4, cex.lab=1.7, cex.main=1.5)
```

```{r}

```